---
- name: Get port details and MAC-addresses
  hosts: all
  gather_facts: false
  connection: local
 
  vars:
  password: "cisco"
  user: "admin"
  server: "{{ ansible_host }}"
  validate_certs: no
  server_port: 443
 
  
  tasks:
   - name: Accespt ansible net hostname
     ios_facts:
        gather_subset: all
   - name: Save your show command to register
     ios_command:
      commands: 'show mac address-table dynamic'
     register: output
