---
- name: Get port details and MAC-addresses
  hosts: all
  gather_facts: false
  connection: local
 
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "admin"
      password: "cisco"
 
  
  tasks:
- name: ios show commands
  ios_command:
    commands: 
       -show mac address-table dynamic
    provider: "{{ cli }}"
