---
- name: Get port details and MAC-addresses
  hosts: all
  gather_facts: false
  connection: local
 
  vars:
    cli:
      username: "admin"
      password: "cisco"
 
  
  tasks:
    - name: Save your show command to register
      ios_command:
      commands: 'show mac address-table dynamic'
      provider: "{{ cli }}"
